name = "spun-moviebox"
main = "src/index.ts"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

[vars]


[[routes]]
# Update with your actual Cloudflare zone if using custom domain
pattern = "moviebox.byspun.xyz/*"
zone_name = "byspun.xyz"

